port: 8001
model: "Qwen/Qwen2-0.5B"
served-model-name: 
- "model1"
- "model2"
max-loras: 2
max-cpu-loras: 5
max-num-seqs: 5
lora-modules:
- '{"name":"lora1","path":"/path/to/lora1"}'
- '{"name":"lora2","path":"/path/to/lora2"}'
mode: "random"
time-to-first-token: 2000
inter-token-latency: 1000
kv-cache-transfer-latency: 100
seed: 100100100
